name: Create Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  create_tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/iala_ms2_maritime_service.docx
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}