name: Create Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  create_tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install mermaid-cli
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Process Mermaid Diagrams
        run: |
          for file in $(find . -name "*.md"); do
            mmdc -e png -b transparent -i $file -o $file
          done

      - name: Convert How To Contribute to Word (.docx) with Pandoc
        uses: docker://pandoc/core:3.1
        with:
          args: >-  # Use multi-line string
            --standalone
            -f markdown+rebase_relative_paths+markdown_in_html_blocks
            --lua-filter source/utils/parse_html_tables.lua
            -F pandoc-crossref
            --citeproc
            --csl resources/ieee-with-url.csl
            --bibliography source/bibliography/bibliography.bib
            --reference-doc=resources/iala_guideline_template_body.docx
            --output=output/how_to_contribute.docx
            source/howto/metadata.md
            source/howto/how_to_contribute.md

      - name: Convert Guideline body to Word (.docx) with Pandoc
        uses: docker://pandoc/core:3.1
        with:
          args: >-  # Use multi-line string
            --standalone
            -f markdown+rebase_relative_paths+markdown_in_html_blocks
            --lua-filter source/utils/parse_html_tables.lua
            -F pandoc-crossref
            --citeproc
            --csl resources/ieee-with-url.csl
            --bibliography source/bibliography/bibliography.bib
            --reference-doc=resources/iala_guideline_template_body.docx
            --output=output/body.docx
            source/guideline/exec_summary.md
            source/guideline/metadata.md
            source/guideline/introduction.md
            source/guideline/user_needs.md
            source/guideline/features.md
            source/guideline/guiding_principles.md
            source/guideline/business_process.md
            source/guideline/definitions.md
            source/guideline/abbreviations.md
            source/guideline/references.md
            source/guideline/annex-a.md

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-docx==1.1.0
          pip install docxcompose==1.4.0

      - name: Concatenate Guideline front matter and body
        run: |
          python source/utils/combine_docx.py

      - name: Upload document to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/iala_ms2_maritime_service.docx
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}